spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.29.229.14:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: zhaorui108
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      max-lifetime: 0
  jackson:
    time-zone: GMT+8

    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8088

# Change Database location before wrapping

# Server address is 147.8.139.123
# username: jeremyzhao
# password: iLab@1001HKU
# server:
#  port: 80

